### ISSUE TITLE
throw new Error(`Invalid arguments: ${error.message}`);

### ISSUE THREAD

**Issue by xx2new** [veo-labs/ldap-server-mock#12]
Hey i get this error when i will start ldap-server ...

$ node node_modules/ldap-server-mock/server.js --conf=/tmp/ldap-server-mock-conf.json --database=/tmp/users.json

/tmp/ldap/node_modules/ldap-server-mock/server.js:26
  throw new Error(`Invalid arguments: ${error.message}`);
  ^

Error: Invalid arguments: /tmp/users.json: Unexpected token [ in JSON at position 119
    at Object.<anonymous> (/tmp/ldap/node_modules/ldap-server-mock/server.js:26:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

Do you have any idea why i get this error ?

Thank you

**Comment by maxime-beguin** [comment]
Hi!

@xx2new : As the error says your **users.json** file doesn't seem to be a valid JSON file (`Error: Invalid arguments: /tmp/users.json: Unexpected token [ in JSON at position 119`)

**Comment by benoit-romito** [comment]
Hi @maxime-beguin, I had the same error in my `server.conf`. I solved it by putting the server config into an array : 
```
[
  {
  "port": 3004,
  "userLoginAttribute": "cn",
  "searchBase": "dc=test",
  "searchFilter": "(&(objectclass=person)(cn={{username}}))"
  }
]
```
It seems to  do the trick :

`LDAP server listening on port 3004`

but I'm not sure if it's the good fix.
